### PR TITLE
Update project-ideas.md

### PR DESCRIPTION
**Pull request by Kresimir235**

### CODE REVIEW

**Review by BorisJegorovic — COMMENTED** [review]
We should follow stacking from original source (e.g. _Urk. IV, 613, 17_).

**Review by BorisJegorovic — CHANGES_REQUESTED** [review]
We should follow stacking from the original source (e.g. Urk. IV, 613, 17).

**Comment by Kresimir235** [comment]
Definitely, if the source is available and is in hieroglyphic. When the source is in hieratic, the stacking is somewhat different. However, for the most part, Erman and Grapow already do follow stacking from the original sources, and when various sources have different stacking, Erman and Grapow list the most common one, so that's good enough for most purposes.

**Review by BorisJegorovic — CHANGES_REQUESTED** [review]
In our database website, we should have all possible hieroglyphic variants of one word. Add changes we discused into project-ideas.md file.

**Review by BorisJegorovic — APPROVED** [review]

**Review by BorisJegorovic — APPROVED** [review]

**Pull request closed without merging**
